name: Build and test with Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test-win:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare conda environment
      shell: cmd
      run: |
        rem Note: Conda VC setenv-script works only with cmd on Win
        rem Source conda hook
        set CONDA=C:\Miniconda
        call %CONDA%\condabin\conda_hook.bat
        call conda create -n mstruct-env -y -c conda-forge python=3.6 libblas=*=*mkl boost=1.66 lapack fftw gsl scons bzip2 git vs2019_win-64 
        call conda activate mstruct-env
    - name: Make distribution
      shell: cmd
      run: |
        set CONDA=C:\Miniconda
        call %CONDA%\condabin\conda_hook.bat
        call conda info --envs
        call conda activate mstruct-env
        rem Get conda env prefix
        call conda info --json | grep default_prefix > _tmp_path1.txt
        (for /f tokens^=3^,4^,*^ delims^=^" %%a in (_tmp_path1.txt) do echo %%b) > _tmp_path2.txt
        for /f "usebackq tokens=*" %%i in (`cat _tmp_path2.txt`) do (
          set P=%%i
        )
        set P=%P:\\=\%
        echo conda_prefix: %P%
        mkdir dist\mstruct
        echo "directory created"
        copy %P%\Library\bin\fftw3.dll dist\mstruct
        copy %P%\python36.dll dist\mstruct
        copy %P%\Library\bin\boost_python3.dll dist\mstruct
        copy %P%\Library\bin\boost_numpy3.dll dist\mstruct
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: dist-win
        path: dist
